stages:
  - init
  # - execute

jobs:
  - name: myFirstInitJob
    stage: init
    image: ubuntu:latest
    vars:
      FIRST_VAR: "foo"
      SECOND_VAR: 4
    action:
      script:
        - echo "Hello World!"
        - echo "I am still here"
        - | 
          sleep 10
          echo "boo"

  - name: mySecondInitJob
    stage: init
    dependencies:
      - myFirstInitJob
    image: ubuntu:latest
    vars:
      FIRST_VAR: "foo"
      SECOND_VAR: "EMV"
    action:
      script:
        - echo "Wecome!"

  - name: myThirdInitJob
    stage: init
    image: ubuntu:latest
    vars:
      FIRST_VAR: "foo"
      SECOND_VAR: ":)"
    action:
      script:
        - echo "Bye!"

  # - name: myExecuteJob
  #   stage: execute
  #   dependencies:
  #     - mySecondInitJob
  #   image: sandbox
  #   vars:
  #     FIRST_VAR: "foo"
  #     SECOND_VAR: 4
  #   action:
  #     terraform:
  #       dir: my_terraform
